# Generated by Django 6.0.1 on 2026-01-14 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='start_time',
        ),
        migrations.AddField(
            model_name='show',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='show',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
