# Generated by Django 6.0.1 on 2026-01-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0002_remove_show_start_time_show_date_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
